---
title: '**【Daily Living Water】**'
date: '*2022 May*'
output: html_document
---

****
#### **May 13**, Matthew 4:23~25, [Reading together](https://www.youtube.com/watch?v=X9PdL9EYerU)

* 【Teaching and Healing】

**Walking along the beach of Lake Galilee, Jesus saw two brothers: Simon (later called peter) and Andrew. They were fishing, throwing their nets into the lake, It was their regular work. Jesus said to them, "Come with me, I'll make a new kind of fisherman out of you. I'll show you how to catch men and women instead of perch and bass." They didn't ask questions, but simply dropping their nets and followed.**

**A short distance down the beach they came upon another pair of brothers, James and John, Zebedee's sons. These two were sitting in the boat with their father, Zebedee, mending their fishnets. Jesus made the same offer to them, and they were just as quick to follow, abandoning boat and father.**

****
#### **May 14**, Matthew 5:1~12, [Reading together](https://www.youtube.com/watch?v=2OCs6ve-HsU)

* 【You're Blessed】

**When Jesus saw his ministry drawing huge crowds, he climbed a hillside. Those who were apprenticed to him, the committed, he sat down and taught his climbing companions. This is what he said:**

**"You're blessed when you're at the end of your rope. With less of you there is more of God and his rules.**
**"You're blessed when you feel you've lost what is most dear to you. Only then can you be embraced by the One most dear to you.**
**"You're blessed when you're content with just who you are--no more, no less. That's the moment you find yourselves proud owners of everything that can't be bought.**
**"You're blessed when you've worked up a good appetite for God. He's food and drink in the best meal you'll ever eat.**
**"You're blessed when you care. At the moment of being 'care-full', you find yourselves cared for.**
**"You're blessed when you get your inside world--your mind and heart--put right. Then you can see God in the outside world.**
**"You're blessed when you can show people how to cooperate instead of compete or fight. That's when you discover who you really are, and your place in God's family.**
**"You're blessed when your commitment to God provokes persecution. The persecution drives you even deeper into God's kingdom.**

**"Not only that--count yourselves blessed every time people put you down or throw you out or speak lies about you to discredit me. What it means is that the truth is too close for comfort and they are uncomfortable. You can be glad when that happens--give a cheer,even!--for though they don't like it, I do! And all heaven applauds. And know that you are in good company. My prophets and witnesses have always gotten into this kind of trouble."**

****

#### **May 16**, Matthew 5:13~16, [Reading together](https://www.youtube.com/watch?v=zNDJ6fA5yz4)

* 【Salt and light】

**"Let me tell you why you are here. You're here to be salt-seasoning that brings out the God-flavors of this earth. If you lose your saltiness, how will people taste godliness? You've lost your usefulness and will end up in the garbage.**

**"Here's another way to put it: You're here to be light, bringing out the God-colors in the world. God is not a secret to be kept. We're going public with this, as public as a city on a hill. If I make you light-bearers, you don't think I'm going to hide you under a bucket, do you? I'm putting you on  a light stand. Now that I've put you on the hilltop, on a light stand--shine! Keep open house, be generous with your lives. By opening up to others, you'll prompt people to open up with God, this generous Father in heaven.**

****

#### **May 17**, Matthew 5:17~20, [Reading together](https://www.youtube.com/watch?v=oytROS6xue8&ab_channel=%E5%8F%B0%E4%B8%AD%E5%BF%A0%E5%AD%9D%E8%B7%AF%E9%95%B7%E8%80%81%E6%95%99%E6%9C%83)

* 【Completing God's Law】

**"Don't suppose for a minute that I have come to demolish the Scriptures--either God's Law or Prophets. I'm not here to demolish but to complete. I am going to put it all together, pull it all together in a vast panorama. God's Law is more real and lasting than the stars in the sky and the ground at your feet. Long after the stars burn out and earth wears out, God's Law will be alive and working.**

**"Trivialize even the smallest item in God's Law and you will only have trivialized yourself. But take it seriously, show the way for others, and you will find the honor in the kingdom. Unless you do far better than the Pharisees in the matters of right living, you won't know the first thing about entering the kingdom.**

****

#### **May 18**, Matthew 5:21~26, [Reading together](https://www.youtube.com/watch?v=f29967qzkCM)

*  【Murder】

**"You're familiar with the command to the ancients, 'Do not murder.' I'm telling you that anyone who is so much as angry with a brother or sister is guilty of murder. Carelessly call a brother 'idiot!' and you just might find yourself hauled into court. Thoughtlessly yell 'stupid!' at a sister and you are on a brink of hellfire. The simple moral fact is that words kill.**

**"This is why I want you to conduct yourself in these matters. If you enter your place of worship and, about to make an offering, you suddenly remember a grudge as friend has against you, abandon your offering, leave immediately, go to this friend and make things right. Then and only then, come back and work things out with God.**

**"Or say you're out on the street and an old enemy accosts you. Don't lose a minute. Make the first move; make things right with him. After all, if you leave the first move to him, knowing his track record, you're likely to end up in court, maybe even jail. If that happens, you won't get out without a stiff fine.**

****