---
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
---

<body style = "background:#4478bc;color:#e1f1fb;padding-top:30px;">

## **Matches Data Visualization**

****

```{r include=FALSE}
library(imputeTS)
library(knitr)
library(dplyr)
library(flextable)
library(magrittr)
library(kableExtra)
library(tidytext)
library(tidyverse)
library(plot.matrix)
library(stringr)
library(ggpubr)
library(highcharter)
library(ggpubr)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(viridisLite)
library(Rtsne)
library(qvalue)
library(jaccard)
library(lsa)
library(patchwork)
library(plotly)
load("Rdata/MatchPlotlys.RData")
```

### **G-2**
<h5>第1週-女 2：臺北鯨華 vs 高雄台電 (10月14日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_1
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_1
```


### **G-8**
<h5>第2週-女 8：新北中纖 vs 臺北鯨華 (11月04日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_2
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_2
```


### **G-12**
<h5>第2週-女 12：臺北鯨華 vs 凱撒飯店連鎖 (11月05日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_3
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_3
```


### **G-13**
<h5>第3週-女 13：臺北鯨華 vs 極速超跑 (11月11日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_4
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_4
```


### **G-16**
<h5>第3週-女 16：高雄台電 vs 臺北鯨華 (11月12日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_5
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_5
```


### **G-26**
<h5>第5週-女 26：高雄台電 vs 臺北鯨華 (11月25日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_6
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_6
```


### **G-28**
<h5>第5週-女 28：極速超跑 vs 臺北鯨華 (11月26日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_7
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_7
```


### **G-43**
<h5>第8週-女 43：極速超跑 vs 臺北鯨華 (12月16日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_8
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_8
```


### **G-46**
<h5>第8週-女 46：臺北鯨華 vs 凱撒飯店連鎖 (12月17日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_9
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_9
```


### **G-49**
<h5>第9週-女 49：新北中纖 vs 臺北鯨華 (12月23日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_10
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_10
```


### **G-52**
<h5>第9週-女 52：臺北鯨華 vs 新北中纖 (12月24日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_11
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_11
```


### **G-58**
<h5>第10週-女 58：臺北鯨華 vs 凱撒飯店連鎖 (01月07日)</h5>

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_positions_12
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
MatchPlotly_teams_12
```


### **G-78**
<h5>第13週13-女 78：新北中纖 vs 臺北鯨華 (01月28日)</h

```{r warning=FALSE, message=FALSE, echo=FALSE}
#MatchPlotly_positions_13
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
#MatchPlotly_teams_13
```


